export const TASKS = {
  SET_ALL_TASKS: 'SET_ALL_TASKS',
  SET_CURRENT_TASK: 'SET_CURRENT_TASK',
  SET_COMMENT: 'SET_COMMENT',
  SET_EXPERT: 'SET_EXPERT'
}

export const USERS = {
  SET_ALL_USERS: 'SET_ALL_USERS',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_UPDATE_USER: 'SET_UPDATE_USER'
}